### ISSUE TITLE
Role ID

### ISSUE THREAD

**Issue by daveidsww** [justIeo/immigration-bot#1]
Roblox doesn't allow me to right-click on roles.

**Comment by justIeo** [comment]
What happens if you try? Nothing?

**Comment by u-x** [comment]
Here's an alternative method:

1. Download BTRoblox for Chrome. https://chrome.google.com/webstore/detail/btroblox-making-roblox-be/hbkpclpemjeibhioopcebchdmohaieln?hl=en-US
2. Right click the role.
3. Hover over Copy role, and go to "Copy role ID."
